=== bioub/Formation_XML_2019_04/Exemples/xsd/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="contacts">
    	
        <xsd:complexType>
        	<xsd:sequence>
        		<xsd:element name="contact" maxOccurs="unbounded"
        			minOccurs="1">
        			<xsd:complexType>
                        <xsd:all>
        					<xsd:element name="prenom" type="xsd:string">
        					</xsd:element>
        					<xsd:element name="nom" type="xsd:string">
        					</xsd:element>
        					<xsd:element name="adresse">
        						<xsd:complexType>
                                    <xsd:all>
        								<xsd:element name="ville" type="xsd:string">
        								</xsd:element>
        								<xsd:element
        									name="codePostal">
        									<xsd:simpleType>
        										<xsd:restriction
        											base="xsd:string">
        											<xsd:pattern
        												value="\d{5}">
        											</xsd:pattern>
        										</xsd:restriction>
        									</xsd:simpleType>
        								</xsd:element>
                                    </xsd:all>
        						</xsd:complexType>
        					</xsd:element>
                        </xsd:all>
        			</xsd:complexType>
        		</xsd:element>
        	</xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bioub/Formation_XML_2019_04/Exemples/xsd/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contacts.xsd">
	<contact>
		<prenom>Jean</prenom>
		<nom>Dupont</nom>
		<adresse>
			<ville>Paris</ville>
			<codePostal>75013</codePostal>
		</adresse>
	</contact>
	<contact>
		<prenom>Eric</prenom>
		<nom>Martin</nom>
		<adresse>
			<ville>Marseille</ville>
			<codePostal>13001</codePostal>
		</adresse>
	</contact>
</contacts>
